INSERT INTO CHECKS (DATE) VALUES ({ts '2012-09-17 18:47:52'});
INSERT INTO CHECKS (DATE) VALUES ({ts '2012-09-18 18:47:52'});

INSERT INTO POSITIONS (NAME) VALUES ('Test_position');
INSERT INTO POSITIONS (NAME) VALUES ('Test2_position');

INSERT INTO SUPPLIERS (NAME) VALUES ('Test_supplier');
INSERT INTO SUPPLIERS (NAME) VALUES ('Test2_supplier');

INSERT INTO INGREDIENTS (NAME) VALUES ('Test_ingredient');
INSERT INTO INGREDIENTS (NAME) VALUES ('Test2_ingredient');

INSERT INTO DISH_CATEGORIES (NAME) VALUES ('Test_dish_category');
INSERT INTO DISH_CATEGORIES (NAME) VALUES ('Test2_dish_category');

INSERT INTO DISHES (NAME, PRICE) VALUES ('Test_dish', 10);
INSERT INTO DISHES (NAME, PRICE) VALUES ('Test2_dish', 20);

INSERT INTO EMPLOYEES (POSITION_ID, NAME, SALARY) VALUES (1, 'Test_employee', 10);
INSERT INTO EMPLOYEES (POSITION_ID, NAME, SALARY) VALUES (2, 'Test2_employee', 20);

INSERT INTO ORDERS (DISH_ID, CHECK_ID, ORDER_DATE, PREPARATION_DATE, SERVICE_DATE) VALUES (1, 1, {ts '2012-09-17 18:47:52'}, {ts '2012-09-17 18:47:52'}, {ts '2012-09-17 18:47:52'});
INSERT INTO ORDERS (DISH_ID, CHECK_ID, ORDER_DATE, PREPARATION_DATE, SERVICE_DATE) VALUES (2, 2, {ts '2012-09-18 18:47:52'}, {ts '2012-09-18 18:47:52'}, {ts '2012-09-18 18:47:52'});

INSERT INTO ORDERS2EMPLOYEES (ORDER_ID, EMPLOYEE_ID) VALUES (1, 1);
INSERT INTO ORDERS2EMPLOYEES (ORDER_ID, EMPLOYEE_ID) VALUES (2, 2);

INSERT INTO SUPPLIERS2INGREDIENTS (INGREDIENT_ID, SUPPLIER_ID) VALUES (1, 1);
INSERT INTO SUPPLIERS2INGREDIENTS (INGREDIENT_ID, SUPPLIER_ID) VALUES (2, 2);

INSERT INTO DISHES2INGREDIENTS (INGREDIENT_ID, DISH_ID) VALUES (1, 1);
INSERT INTO DISHES2INGREDIENTS (INGREDIENT_ID, DISH_ID) VALUES (2, 2);

INSERT INTO DISHES2DISH_CATEGORIES (DISH_CATEGORY_ID, DISH_ID) VALUES (1, 1);
INSERT INTO DISHES2DISH_CATEGORIES (DISH_CATEGORY_ID, DISH_ID) VALUES (2, 2);