CREATE TABLE IF NOT EXISTS "CHECKS" (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    DATE TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS "POSITIONS" (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS "POSITIONS_INDEX" ON "POSITIONS" (NAME);

CREATE TABLE IF NOT EXISTS "SUPPLIERS" (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) UNIQUE,
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS "SUPPLIERS_INDEX" ON "SUPPLIERS" (NAME);

CREATE TABLE IF NOT EXISTS "INGREDIENTS" (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) UNIQUE,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS "DISH_CATEGORIES" (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) UNIQUE,
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS "DISH_CATEGORIES_INDEX" ON "DISH_CATEGORIES" (NAME);

CREATE TABLE IF NOT EXISTS "DISHES" (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    PRICE INTEGER NOT NULL,
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS "DISHES_INDEX" ON "DISHES" (NAME);

CREATE TABLE IF NOT EXISTS "EMPLOYEES" (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    POSITION_ID INTEGER NOT NULL,
    NAME VARCHAR(255),
    SALARY DECIMAL NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT "EMPLOYEES_POSITION_ID" FOREIGN KEY (POSITION_ID) REFERENCES "POSITIONS"(ID)
);

CREATE TABLE IF NOT EXISTS "ORDERS" (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    DISH_ID INTEGER NOT NULL,
    CHECK_ID INTEGER,
    ORDER_DATE TIMESTAMP,
    PREPARATION_DATE TIMESTAMP,
    SERVICE_DATE TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT "ORDERS_DISH_ID" FOREIGN KEY (DISH_ID) REFERENCES "DISHES"(ID),
    CONSTRAINT "ORDERS_CHECK_ID" FOREIGN KEY (CHECK_ID) REFERENCES "CHECKS"(ID)
);

CREATE TABLE IF NOT EXISTS "ORDERS2EMPLOYEES" (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ORDER_ID INTEGER NOT NULL,
    EMPLOYEE_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT "ORDERS2EMPLOYEES_ORDER_ID" FOREIGN KEY (ORDER_ID) REFERENCES "ORDERS"(ID),
    CONSTRAINT "ORDERS2EMPLOYEES_EMPLOYEE_ID" FOREIGN KEY (EMPLOYEE_ID) REFERENCES "EMPLOYEES"(ID)
);

CREATE TABLE IF NOT EXISTS "SUPPLIERS2INGREDIENTS" (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    INGREDIENT_ID INTEGER NOT NULL,
    SUPPLIER_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT "SUPPLIERS2INGREDIENTS_INGREDIENT_ID" FOREIGN KEY (INGREDIENT_ID) REFERENCES "INGREDIENTS"(ID),
    CONSTRAINT "SUPPLIERS2INGREDIENTS_SUPPLIER_ID" FOREIGN KEY (SUPPLIER_ID) REFERENCES "SUPPLIERS"(ID)
);

CREATE TABLE IF NOT EXISTS "DISHES2INGREDIENTS" (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    INGREDIENT_ID INTEGER NOT NULL,
    DISH_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT "DISHES2INGREDIENTS_INGREDIENT_ID" FOREIGN KEY (INGREDIENT_ID) REFERENCES "INGREDIENTS"(ID),
    CONSTRAINT "DISHES2INGREDIENTS_DISH_ID" FOREIGN KEY (DISH_ID) REFERENCES "DISHES"(ID)
);

CREATE TABLE IF NOT EXISTS "DISHES2DISH_CATEGORIES" (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    DISH_CATEGORY_ID INTEGER NOT NULL,
    DISH_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT "DISHES2DISH_CATEGORIES_DISH_CATEGORY_ID" FOREIGN KEY (DISH_CATEGORY_ID) REFERENCES "DISH_CATEGORIES"(ID),
    CONSTRAINT "DISHES2DISH_CATEGORIES_DISH_ID" FOREIGN KEY (DISH_ID) REFERENCES "DISHES"(ID)
);


